CREATE OR REPLACE TABLE TDP_DEV.BRONZE.WAITLY_STORE_SUMMARY (
    timestamp STRING,
    id STRING,
    external_id STRING,
    name STRING,
    waiting NUMBER,
    no_shows NUMBER,
    parties_served NUMBER,
    guests_served NUMBER,
    reservations_served NUMBER,
    longest_wait NUMBER,
    waiting_online NUMBER,
    wait_time_value FLOAT,
    wait_time_sample_size NUMBER,
    wait_time_minutes_waited NUMBER,
    movingAverage15ByCategoryPickup FLOAT,
    movingAverage15ByCategoryPickupSampleSize NUMBER,
    movingAverage15ByCategoryWalk_in FLOAT,
    movingAverage15ByCategoryWalk_inSampleSize NUMBER,
    movingAverage15ByCategoryExpress FLOAT,
    movingAverage15ByCategoryExpressSampleSize NUMBER,
    movingAverage15ByCategoryDelivery FLOAT,
    movingAverage15ByCategoryDeliverySampleSize NUMBER
);