MERGE INTO tdp.test.tdp_all_sales target
    USING tdp.test.tdp_all_sales_stage source
    ON target.order_id = source.order_id 
    AND target.order_item_id = source.order_item_id
    WHEN MATCHED 
    AND target.accounting_date BETWEEN DATEADD(month, -2, DATEADD(day, 1, LAST_DAY(CURRENT_DATE()))) 
    AND DATEADD(day, -1, CURRENT_DATE())
    THEN UPDATE SET
        data_type = source.data_type,
        source_system = source.source_system,
        source_system_id = source.source_system_id,
        unified_store_id = source.unified_store_id,
        order_created_datetime = source.order_created_datetime,
        order_completed_datetime = source.order_completed_datetime,
        order_created_datetime_utc = source.order_created_datetime_utc,
        order_completed_datetime_utc = source.order_completed_datetime_utc,
        accounting_date = source.accounting_date,
        order_created_by = source.order_created_by,
        order_completed_by = source.order_completed_by,
        order_fulfillment_method = source.order_fulfillment_method,
        mrw_flag = source.mrw_flag,
        ecomm_order_id = source.ecomm_order_id,
        customer_id = source.customer_id,
        unified_customer_id = source.unified_customer_id,
        product_id = source.product_id,
        unified_product_id = source.unified_product_id,
        batch = source.batch,
        order_type = source.order_type,
        invoice_type = source.invoice_type,
        gross_sales = source.gross_sales,
        discount_amount = source.discount_amount,
        net_sales = source.net_sales,
        quantity = source.quantity,
        cogs = source.cogs,
        cost = source.cost,
        pull_datetime = source.pull_datetime,
        pull_datetime_utc = source.pull_datetime_utc,
        glue_pull_datetime_utc = source.glue_pull_datetime_utc
    WHEN NOT MATCHED THEN INSERT VALUES (
        source.data_type,
        source.source_system,
        source.source_system_id,
        source.unified_store_id,
        source.order_id,
        source.order_item_id,
        source.order_created_datetime,
        source.order_completed_datetime,
        source.order_created_datetime_utc,
        source.order_completed_datetime_utc,
        source.accounting_date,
        source.order_created_by,
        source.order_completed_by,
        source.order_fulfillment_method,
        source.mrw_flag,
        source.ecomm_order_id,
        source.customer_id,
        source.unified_customer_id,
        source.product_id,
        source.unified_product_id,
        source.batch,
        source.order_type,
        source.invoice_type,
        source.gross_sales,
        source.discount_amount,
        source.net_sales,
        source.quantity,
        source.cogs,
        source.cost,
        source.pull_datetime,
        source.pull_datetime_utc,
        source.glue_pull_datetime_utc
    );