 
CREATE TABLE IF NOT EXISTS TDP_DEV.STAGING.SENDGRID_EVENTS_RAW_cicd (
 ID VARCHAR(16777216) DEFAULT UUID_STRING(),
 JSON_CONTENT VARIANT,
 PROCESSED BOOLEAN DEFAULT FALSE,
 CREATED_AT_UTC TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
 PROCESSED_AT_UTC TIMESTAMP_LTZ(9)
);;
